### PR TITLE
added solutions related to strings and maths

### PR DESCRIPTION
**Pull request by NiruBhai**
I have found a solution for " Construct the Rectangle " as well as suggested alternative solution for " To Lower Case " leetcode questions. I'm actually a newbie in Git Hub. If I have made any mistake in the procedure or the code please help me

### CODE REVIEW

**Comment by Siddhant-K-code** [comment]
Thank you for your contribution, Please change the title name `Please merge pull request` to a Category of the solution you added, suppose if you contributed Binary Search Problems, Add `added Binary Search Problems`

**Review by Siddhant-K-code — CHANGES_REQUESTED** [review]
Please change the title name Please merge pull request to a Category of the solution you added, suppose if you contributed Binary Search Problems, Add added Binary Search Problems

**Comment by NiruBhai** [comment]
Thank you for the mail. I will do as requested by you.

Niranjan K Sabu

**Comment by NiruBhai** [comment]
I have changed the title

**Pull request merged**
